#!/bin/bash

# Vercel Environment Variables Update Script
# This script helps update environment variables for the Vercel project

echo "🔧 Vercel Environment Variables Update Helper"
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Go to: https://vercel.com/dashboard"
echo "2. Select your project (No.1)"
echo "3. Go to: Settings → Environment Variables"
echo ""
echo "4. Delete ALL existing POSTGRES_* variables"
echo ""
echo "5. Click 'Add New' and add these variables:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Variable 1:"
echo "Key:   POSTGRES_URL"
echo "Value: postgresql://neondb_owner:npg_Yr0Q5mLcPVWq@ep-fancy-dust-ahpdqryu-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require"
echo "Environments: ✓ Production ✓ Preview ✓ Development"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Variable 2:"
echo "Key:   POSTGRES_PRISMA_URL"
echo "Value: postgresql://neondb_owner:npg_Yr0Q5mLcPVWq@ep-fancy-dust-ahpdqryu-pooler.c-3.us-east-1.aws.neon.tech/neondb?connect_timeout=15&sslmode=require"
echo "Environments: ✓ Production ✓ Preview ✓ Development"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Variable 3:"
echo "Key:   POSTGRES_URL_NON_POOLING"
echo "Value: postgresql://neondb_owner:npg_Yr0Q5mLcPVWq@ep-fancy-dust-ahpdqryu.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require"
echo "Environments: ✓ Production ✓ Preview ✓ Development"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Variable 4:"
echo "Key:   POSTGRES_USER"
echo "Value: neondb_owner"
echo "Environments: ✓ Production ✓ Preview ✓ Development"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Variable 5:"
echo "Key:   POSTGRES_HOST"
echo "Value: ep-fancy-dust-ahpdqryu-pooler.c-3.us-east-1.aws.neon.tech"
echo "Environments: ✓ Production ✓ Preview ✓ Development"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Variable 6:"
echo "Key:   POSTGRES_PASSWORD"
echo "Value: npg_Yr0Q5mLcPVWq"
echo "Environments: ✓ Production ✓ Preview ✓ Development"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Variable 7:"
echo "Key:   POSTGRES_DATABASE"
echo "Value: neondb"
echo "Environments: ✓ Production ✓ Preview ✓ Development"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "6. After adding all variables, Vercel will automatically redeploy"
echo "7. Wait 1-2 minutes for deployment to complete"
echo ""
echo "✅ Done! Your site should work at: https://no-1-rust.vercel.app/"
